name: e_commerce
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  go_router: ^14.2.3
  flutter_riverpod: ^2.5.1
  dropdown_button2: ^2.3.9
  uuid: ^4.4.2
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  intl: ^0.19.0
  flutter_login: ^5.0.0
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
